//Project Euler
//
//PROBLEM 2
//Solution by Joseph Goodknight
//j@JosephGoodknight.com

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <iostream>
#include <vector>
#include <list>

int main() {
	int LESS_THAN =  4000000;

	int total = 0;

	int lastFib = 1;
	int secondToLastFib = 1;

	int currentFib = 2;

	int temp = 0;

	while(currentFib < LESS_THAN) {
		std::cout << currentFib << "\n";
		if (currentFib % 2 == 0) 
		{
			total = total + currentFib;
		}
		secondToLastFib = lastFib;
		lastFib = currentFib;

		currentFib = lastFib + secondToLastFib;

	}

	std::cout << "\nANSWER: " << total <<"\n";
}
